### ISSUE TITLE
Applicator hotlink shows twice on the contents summary

### ISSUE THREAD

**Issue by voximity** [brickadia/book#6]
See title.

**Comment by qoh** [comment]
This doesn't seem to be the case anymore, otherwise please give reproduction steps.

**Comment by voximity** [comment]
Yep, this seems to have been fixed by [this commit](https://github.com/brickadia/book/commit/977c3d589690355854a0a55e259590f88534da65#diff-a7e3a664e97aa06240065215cf96d786578e4609d0b42fdfe14be434bc97b22f). Thanks!
